FROM php:7.2-cli
ENV COMMAND_NAME think

RUN docker-php-ext-install -j$(nproc) iconv pdo_mysql mysqli bcmath mysqli sockets bcmath
#RUN  docker-php-ext-install -j$(nproc) gd

RUN pecl install redis-4.0.1 \
    && docker-php-ext-enable redis\
